POST http://localhost:4000/Videos
Content-Type: application/json 

{
    "title": "video 01"
}

###


GET  http://localhost:4000/Videos

###

PUT http://localhost:4000/Videos/aebb085b-a551-4f02-ac64-b6ebc509945e
Content-Type: application/json 

{
    "title": "videos 05"
}

###

DELETE  http://localhost:4000/Videos/af23f9a7-0b1c-42b4-9c35-0b49137a9ff9